import mongoose from 'mongoose'
import dotenv from 'dotenv'
import Product from './models/Product.js'

dotenv.config()

const allProducts = [

  // ── MAIZE FLOUR ──
  { name: 'Riri Ugali 2kg',        retailPrice: 1950, category: 'Maize Flour' },
  { name: 'Riri Ugali 1kg',        retailPrice: 1980, category: 'Maize Flour' },
  { name: 'Leah Premium 2kg',      retailPrice: 2070, category: 'Maize Flour' },
  { name: 'Leah Premium 1kg',      retailPrice: 2090, category: 'Maize Flour' },
  { name: 'Nice Premium 2kg',      retailPrice: 2280, category: 'Maize Flour' },
  { name: 'Nice Premium 1kg',      retailPrice: 2300, category: 'Maize Flour' },
  { name: 'Raha Premium 2kg',      retailPrice: 2280, category: 'Maize Flour' },
  { name: 'Raha Premium 1kg',      retailPrice: 2300, category: 'Maize Flour' },
  { name: 'Spenza 2kg',            retailPrice: 2150, category: 'Maize Flour' },
  { name: 'Spenza 1kg',            retailPrice: 2180, category: 'Maize Flour' },
  { name: 'Soko Ugali 2kg',        retailPrice: 1900, category: 'Maize Flour' },
  { name: 'Soko Ugali 1kg',        retailPrice: 1920, category: 'Maize Flour' },
  { name: '210 Ugali 2kg',         retailPrice: 1880, category: 'Maize Flour' },
  { name: '210 Ugali 1kg',         retailPrice: 1900, category: 'Maize Flour' },
  { name: 'Pembe Ugali 2kg',       retailPrice: 1900, category: 'Maize Flour' },
  { name: 'Pembe Ugali 1kg',       retailPrice: 1920, category: 'Maize Flour' },
  { name: 'Diamond Ugali 2kg',     retailPrice: 1600, category: 'Maize Flour' },
  { name: 'Diamond Ugali 1kg',     retailPrice: 1630, category: 'Maize Flour' },
  { name: 'Jasiri Ugali 2kg',      retailPrice: 1630, category: 'Maize Flour' },
  { name: 'Jasiri Ugali 1kg',      retailPrice: 1650, category: 'Maize Flour' },
  { name: 'Rania Ugali 2kg',       retailPrice: 1600, category: 'Maize Flour' },
  { name: 'Rania Ugali 1kg',       retailPrice: 1630, category: 'Maize Flour' },
  { name: 'Dhahabu Ugali 2kg',     retailPrice: 1570, category: 'Maize Flour' },
  { name: 'Dhahabu Ugali 1kg',     retailPrice: 1600, category: 'Maize Flour' },
  { name: 'Miale Ugali 2kg',       retailPrice: 1570, category: 'Maize Flour' },
  { name: 'Miale Ugali 1kg',       retailPrice: 1600, category: 'Maize Flour' },

  // ── COOKING FAT ──
  { name: 'Samli 10kg',            retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Pika 10kg',             retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Seagull 10kg',          retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Sunshine 10kg',         retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Zulfa 10kg',            retailPrice: 2550, category: 'Cooking Fat' },

  // ── SALAD OIL ──
  { name: 'Rina Salad Oil 5ltrs 4pcs',     retailPrice: 5450, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 3ltrs 6pcs',     retailPrice: 4720, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 2ltrs 8pcs',     retailPrice: 4250, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 1ltr 12pcs',     retailPrice: 3390, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 500ml 12pcs',    retailPrice: 1750, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 250ml 24pcs',    retailPrice: 1900, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 1ltr',         retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 2ltrs',        retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 3ltrs',        retailPrice: 4650, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 5ltrs',        retailPrice: 5150, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 20ltrs',       retailPrice: 5050, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 1ltr',           retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 2ltrs',          retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 3ltrs',          retailPrice: 4650, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 5ltrs',          retailPrice: 5150, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 20ltrs',         retailPrice: 5050, category: 'Salad Oil' },
  { name: 'Fresh Fri 250ml 24pcs',         retailPrice: 2350, category: 'Salad Oil' },
  { name: 'Fresh Fri 500ml 12pcs',         retailPrice: 2150, category: 'Salad Oil' },
  { name: 'Fresh Fri 1ltr 12pcs',          retailPrice: 3700, category: 'Salad Oil' },
  { name: 'Fresh Fri 2ltrs 6pcs',          retailPrice: 3750, category: 'Salad Oil' },
  { name: 'Fresh Fri 3ltrs 6pcs',          retailPrice: 5200, category: 'Salad Oil' },
  { name: 'Fresh Fri 5ltrs 4pcs',          retailPrice: 5550, category: 'Salad Oil' },
  { name: 'Fresh Fri 5ltrs 1pc',           retailPrice: 1370, category: 'Salad Oil' },
  { name: 'Popco Salad Oil 5ltrs',         retailPrice: 1300, category: 'Salad Oil' },
  { name: 'Golden Drop 20ltrs',            retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Pura 20ltrs',                   retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Postman 20ltrs',                retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Postman 10ltrs',                retailPrice: 2600, category: 'Salad Oil' },
  { name: 'Pika Salad Oil 20ltrs',         retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Salit 20ltrs',                  retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Nyota 20ltrs',                  retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Nyota 10ltrs',                  retailPrice: 2600, category: 'Salad Oil' },
  { name: 'Karaih 20ltrs',                 retailPrice: 5050, category: 'Salad Oil' },
  { name: 'Karaih 10ltrs',                 retailPrice: 2600, category: 'Salad Oil' },

  // ── PISHORI RICE ──
  { name: 'Mwea Pure Pishori Rice 25kg',   retailPrice: 3800, category: 'Pishori Rice' },

  // ── PARBOILED RICE ──
  { name: 'Rischi Parboiled 25kg',         retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Raha Parboiled 25kg',           retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Volga Parboiled 25kg',          retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'King Africa Parboiled 25kg',    retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Maarufu Parboiled 25kg',        retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Najah PK386 25kg',              retailPrice: 4200, category: 'Parboiled Rice' },
  { name: 'King Africa PK386 25kg',        retailPrice: 3450, category: 'Parboiled Rice' },
  { name: 'Alrazq 25kg',                   retailPrice: 3650, category: 'Parboiled Rice' },
  { name: 'Mzuri PK386 25kg',              retailPrice: 3600, category: 'Parboiled Rice' },
  { name: 'Zahra 25kg',                    retailPrice: 3900, category: 'Parboiled Rice' },
  { name: 'Shabeel 25kg',                  retailPrice: 4200, category: 'Parboiled Rice' },
  { name: 'Karama 25kg',                   retailPrice: 4300, category: 'Parboiled Rice' },
  { name: 'Hamza Parboiled 25kg',          retailPrice: 4350, category: 'Parboiled Rice' },
  { name: 'ANFAC Long Grain 25kg',         retailPrice: 5700, category: 'Parboiled Rice' },
  { name: 'Mahamood 1121 25kg',            retailPrice: 6000, category: 'Parboiled Rice' },

  // ── BASMATI RICE ──
  { name: 'Joli Marhaba Basmati 25kg',     retailPrice: 3250, category: 'Basmati Rice' },
  { name: 'Azmat Basmati 25kg',            retailPrice: 3250, category: 'Basmati Rice' },
  { name: 'Fzami Poa 25kg',               retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Fzami Karibu 25kg',             retailPrice: 3400, category: 'Basmati Rice' },
  { name: 'Kangore Gold Basmati 25kg',     retailPrice: 3350, category: 'Basmati Rice' },
  { name: 'Sanaa Brown 25kg',              retailPrice: 3450, category: 'Basmati Rice' },
  { name: 'Amne Basmati 25kg',             retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Indus Basmati 25kg',            retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Hanaan Basmati 25kg',           retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Hani Basmati 25kg',             retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Siham Basmati 25kg',            retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Yabal Brown 25kg',              retailPrice: 3800, category: 'Basmati Rice' },
  { name: 'Baraf Brown 25kg',              retailPrice: 3800, category: 'Basmati Rice' },
  { name: 'Halwo Brown 25kg',              retailPrice: 3800, category: 'Basmati Rice' },
  { name: 'Safi Special Sindano 25kg',     retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Mankera Special Sindano 25kg',  retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Indus PK386 25kg',              retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Star Africa PK386 25kg',        retailPrice: 3450, category: 'Basmati Rice' },
  { name: 'Indus 555 25kg',               retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Mahia White 25kg',              retailPrice: 3550, category: 'Basmati Rice' },
  { name: 'Capital White 25kg',            retailPrice: 3650, category: 'Basmati Rice' },
  { name: 'Jawil Gold 25kg',               retailPrice: 3650, category: 'Basmati Rice' },
  { name: 'Fzami Sindano Safi 25kg',       retailPrice: 3200, category: 'Basmati Rice' },
  { name: 'Fzami Sindano Bora 25kg',       retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Anab PK386 25kg',               retailPrice: 3650, category: 'Basmati Rice' },
  { name: 'Hanan PK386 25kg',              retailPrice: 3650, category: 'Basmati Rice' },

  // ── BIRYANI RICE ──
  { name: 'Manaan Biryani 25kg',           retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Maarufu Biryani 25kg',          retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Kuku Biryani 25kg',             retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Dream Africa Biryani 25kg',     retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Indian Biryani 25kg',           retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Indus Biryani Gold 25kg',       retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Raha Biryani 25kg',             retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Sakshi Biryani 25kg',           retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Rischi Biryani 25kg',           retailPrice: 2550, category: 'Biryani Rice' },
  { name: 'Fineese Biryani 25kg',          retailPrice: 2580, category: 'Biryani Rice' },

  // ── MILK ──
  { name: 'Mt Kenya Milk 500ml 18pcs',     retailPrice: 930,  category: 'Milk' },
  { name: 'Mt Kenya Milk 200ml 21pcs',     retailPrice: 520,  category: 'Milk' },
  { name: 'Daima Milk 500ml 18pcs',        retailPrice: 920,  category: 'Milk' },
  { name: 'Brookside Milk 500ml 12pcs',    retailPrice: 750,  category: 'Milk' },
  { name: 'Brookside Milk 200ml 21pcs',    retailPrice: 650,  category: 'Milk' },
  { name: 'Lato Milk 18pcs',               retailPrice: 950,  category: 'Milk' },

  // ── PASTRY & FOOD PRODUCTS ──
  { name: 'Indomie Supermi',               retailPrice: 650,  category: 'Pastry & Food Products' },
  { name: 'Indomie Chicken',               retailPrice: 750,  category: 'Pastry & Food Products' },
  { name: 'Indomie Beef',                  retailPrice: 750,  category: 'Pastry & Food Products' },
  { name: 'Nala Noodles',                  retailPrice: 700,  category: 'Pastry & Food Products' },
  { name: 'Rosa Spaghetti 500g',           retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Nureen Spaghetti 500g',         retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Indus Spaghetti 500g',          retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Siens Spaghetti 500g',          retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Arta Spaghetti',                retailPrice: 2250, category: 'Pastry & Food Products' },
  { name: 'Salsa Spaghetti 500g',          retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Sara Spaghetti 500g',           retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Tak Spaghetti 500g',            retailPrice: 2350, category: 'Pastry & Food Products' },
  { name: 'Tak Macaroni 500g',             retailPrice: 2350, category: 'Pastry & Food Products' },
  { name: 'Hilwa 500g x12',                retailPrice: 800,  category: 'Pastry & Food Products' },
  { name: 'Cerelac 25g x12',               retailPrice: 500,  category: 'Pastry & Food Products' },
  { name: 'Cerelac 50g x12',               retailPrice: 800,  category: 'Pastry & Food Products' },
  { name: 'Cerelac 400g 1pc',              retailPrice: 850,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 37g 2dzn',             retailPrice: 620,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 74g',                  retailPrice: 1160, category: 'Pastry & Food Products' },
  { name: 'Weetabix 112g',                 retailPrice: 2100, category: 'Pastry & Food Products' },
  { name: 'Weetabix 210g Carton',          retailPrice: 8550, category: 'Pastry & Food Products' },
  { name: 'Weetabix 210g Dozen',           retailPrice: 250,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 425g Carton',          retailPrice: 8200, category: 'Pastry & Food Products' },
  { name: 'Weetabix 425g Dozen',           retailPrice: 460,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 850g Carton',          retailPrice: 7300, category: 'Pastry & Food Products' },
  { name: 'Weetabix 850g Dozen',           retailPrice: 700,  category: 'Pastry & Food Products' },
  { name: 'Weetos 420g x8 Carton',         retailPrice: 4350, category: 'Pastry & Food Products' },
  { name: 'Weetos 420g Piece',             retailPrice: 600,  category: 'Pastry & Food Products' },
  { name: 'Salama Oats 1kg x9 Carton',     retailPrice: 2500, category: 'Pastry & Food Products' },
  { name: 'Salama Oats 1kg Piece',         retailPrice: 350,  category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 35g Carton', retailPrice: 1450, category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 35g Piece',  retailPrice: 250,  category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 70g Carton', retailPrice: 1750, category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 70g Piece',  retailPrice: 460,  category: 'Pastry & Food Products' },

  // ── COFFEE, CHOCOLATE & TEA ──
  { name: 'Cocoa Drinking 20g Dozen',          retailPrice: 650,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 90g Dozen',                   retailPrice: 3270,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 200g Carton',                 retailPrice: 5850,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 200g Dozen',                  retailPrice: 530,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 320g Carton',                 retailPrice: 11100, category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 320g Dozen',                  retailPrice: 1000,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Maccoffee Dozen',                   retailPrice: 95,    category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe Dozen',                     retailPrice: 110,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe Outer',                     retailPrice: 750,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 3 in 1 Outer',              retailPrice: 400,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 50g Dozen',                 retailPrice: 3270,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 100g',                      retailPrice: 4900,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 100g Piece',                retailPrice: 430,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 200g Carton',               retailPrice: 8500,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 200g Piece',                retailPrice: 730,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 10g Outer',          retailPrice: 850,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 10g Piece',          retailPrice: 180,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 20g Outer',          retailPrice: 1065,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 20g Piece',          retailPrice: 300,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 160g Dozen',             retailPrice: 2500,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 160g Piece',             retailPrice: 400,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 320g Dozen',             retailPrice: 7100,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 320g Piece',             retailPrice: 630,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 125g Dozen',     retailPrice: 2250,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 125g Piece',     retailPrice: 230,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 225g Dozen',     retailPrice: 3700,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 225g Piece',     retailPrice: 330,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 450g Dozen',     retailPrice: 6920,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 450g Piece',     retailPrice: 650,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Milo 20g Dozen',                    retailPrice: 230,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Kahawa No.1 2 Dozen',               retailPrice: 260,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 1.6g 25pcs',                retailPrice: 300,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 1.6g 100pcs',               retailPrice: 950,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 50g',                       retailPrice: 370,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 100g',                      retailPrice: 670,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 200g',                      retailPrice: 1230,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 15g',                       retailPrice: 150,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 50g',                       retailPrice: 200,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 100g',                      retailPrice: 480,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 250g 6pcs',                 retailPrice: 720,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 500g 6pcs',                 retailPrice: 1140,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 250g',                       retailPrice: 500,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 100g',                       retailPrice: 450,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 50g x10',                    retailPrice: 230,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 15g x50',                    retailPrice: 350,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 15g',                      retailPrice: 150,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 25g',                      retailPrice: 150,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 50g',                      retailPrice: 230,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 100g',                     retailPrice: 450,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 250g Piece',               retailPrice: 130,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 500g Piece',               retailPrice: 200,   category: 'Coffee, Chocolate & Tea' },
  { name: "Melvin's 15g",                      retailPrice: 180,   category: 'Coffee, Chocolate & Tea' },
  { name: "Melvin's 50g",                      retailPrice: 650,   category: 'Coffee, Chocolate & Tea' },
  { name: "Melvin's 100g",                     retailPrice: 650,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Kericho Tea Bags 50s',              retailPrice: 200,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Kericho Tea Bags Envelope 100s',    retailPrice: 300,   category: 'Coffee, Chocolate & Tea' },

  // ── SUGAR ──
  { name: 'Sugar 50kg',            retailPrice: 6800, category: 'Sugar' },
  { name: 'Sugar 25kg',            retailPrice: 3450, category: 'Sugar' },
  { name: 'Kabras Sugar 1kg',      retailPrice: 3250, category: 'Sugar' },
  { name: 'Kabras Sugar 2kg',      retailPrice: 3250, category: 'Sugar' },
  { name: 'Sare Packed Sugar 1kg', retailPrice: 3350, category: 'Sugar' },
  { name: 'Mara Sugar 1kg',        retailPrice: 3350, category: 'Sugar' },

  // ── WHEAT FLOUR ──
  { name: 'Raha Premium Ngano 2kg', retailPrice: 1960, category: 'Wheat Flour' },
  { name: 'Riri Ngano 2kg',         retailPrice: 1870, category: 'Wheat Flour' },
  { name: 'Supreme Ngano 2kg',      retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Lotus Ngano 2kg',        retailPrice: 1930, category: 'Wheat Flour' },
  { name: 'Swan Wheat 2kg',         retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Umoja Ngano 2kg',        retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Umoja Ngano 1kg',        retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Exe Mandazi 2kg',        retailPrice: 2150, category: 'Wheat Flour' },
  { name: 'Self Raising Flour 2kg', retailPrice: 2250, category: 'Wheat Flour' },
  { name: 'Ajab Ngano 2kg',         retailPrice: 2000, category: 'Wheat Flour' },
  { name: 'Ajab Ngano 1kg',         retailPrice: 2020, category: 'Wheat Flour' },
  { name: 'Ajab Ngano 500g',        retailPrice: 1050, category: 'Wheat Flour' },
  { name: 'Ndovu All Purpose 2kg',  retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Ndovu All Purpose 1kg',  retailPrice: 1920, category: 'Wheat Flour' },
  { name: '210 Ngano 2kg',          retailPrice: 1900, category: 'Wheat Flour' },
  { name: '210 Ngano 1kg',          retailPrice: 1920, category: 'Wheat Flour' },
  { name: 'Hodi Ngano 2kg',         retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Hodi Ngano 1kg',         retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Kifaru Ngano 2kg',       retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Kifaru Ngano 1kg',       retailPrice: 1920, category: 'Wheat Flour' },
  { name: 'Pembe Ngano 2kg',        retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Pembe Ngano 1kg',        retailPrice: 1910, category: 'Wheat Flour' },
  { name: 'Pembe Atta Mark 2kg',    retailPrice: 1970, category: 'Wheat Flour' },
  { name: 'Soko Ngano 2kg',         retailPrice: 1900, category: 'Wheat Flour' },

  // ── SALT ──
  { name: 'Kensalt 2kg',   retailPrice: 740, wholesalePrice: 680, category: 'Salt' },
  { name: 'Kensalt 1kg',   retailPrice: 740, wholesalePrice: 680, category: 'Salt' },
  { name: 'Kensalt 500g',  retailPrice: 740, wholesalePrice: 680, category: 'Salt' },
  { name: 'Kensalt 200g',  retailPrice: 280, wholesalePrice: 260, category: 'Salt' },
  { name: 'Kaysalt 2kg',   retailPrice: 680, wholesalePrice: 630, category: 'Salt' },
  { name: 'Kaysalt 1kg',   retailPrice: 680, wholesalePrice: 630, category: 'Salt' },
  { name: 'Kaysalt 500g',  retailPrice: 680, wholesalePrice: 630, category: 'Salt' },

  // ── SPREADS ──
  { name: 'Prestige 10kg',       retailPrice: 3050, wholesalePrice: 2900, category: 'Spreads' },
  { name: 'Prestige 1kg 12pcs',  retailPrice: 4200, wholesalePrice: 3990, category: 'Spreads' },
  { name: 'Prestige 500g',       retailPrice: 3550, wholesalePrice: 3370, category: 'Spreads' },
  { name: 'Prestige 250g',       retailPrice: 2550, wholesalePrice: 2420, category: 'Spreads' },
  { name: 'Blueband 30g Carton', retailPrice: 2650, wholesalePrice: 2100, category: 'Spreads' },
  { name: 'Blueband 100g Carton',retailPrice: 2550, wholesalePrice: 750,  category: 'Spreads' },
  { name: 'Blueband 250g Carton',retailPrice: 6400, wholesalePrice: 1650, category: 'Spreads' },

  // ── YEAST ──
  { name: 'Yeast Sachets Dozen', retailPrice: 220, wholesalePrice: 200, category: 'Yeast' },
  { name: 'Pasha Yeast 450g',    retailPrice: 350, wholesalePrice: 320, category: 'Yeast' },
  { name: 'Acta Yeast 450g',     retailPrice: 350, wholesalePrice: 320, category: 'Yeast' },
  { name: 'Magest Yeast 450g',   retailPrice: 350, wholesalePrice: 320, category: 'Yeast' },

  // ── SPICES ──
  { name: 'Onga Carton',                  retailPrice: 550,  wholesalePrice: 500,  category: 'Spices' },
  { name: 'Royco Cube Outer',             retailPrice: 190,  wholesalePrice: 175,  category: 'Spices' },
  { name: 'Royco Cube Carton',            retailPrice: 4300, wholesalePrice: 4085, category: 'Spices' },
  { name: 'Royco Chicken Sachets Carton', retailPrice: 550,  wholesalePrice: 520,  category: 'Spices' },
  { name: 'Royco Beef Sachets Carton',    retailPrice: 550,  wholesalePrice: 520,  category: 'Spices' },
  { name: 'Pilau Masala Dozen',           retailPrice: 285,  wholesalePrice: 260,  category: 'Spices' },
  { name: 'Curry Powder 2 Dozen',         retailPrice: 120,  wholesalePrice: 110,  category: 'Spices' },
  { name: 'Chapa Mandashi Dozen',         retailPrice: 380,  wholesalePrice: 350,  category: 'Spices' },
  { name: 'Chapa Mandashi Carton',        retailPrice: 2220, wholesalePrice: 2100, category: 'Spices' },
  { name: 'Kensafi Baking Powder',        retailPrice: 1500, wholesalePrice: 1400, category: 'Spices' },

  // ── BAR SOAPS ──
  { name: 'Menengai 800g Carton',   retailPrice: 4200, wholesalePrice: 3990, category: 'Bar Soaps' },
  { name: 'Menengai 800g 5pcs',     retailPrice: 950,  wholesalePrice: 900,  category: 'Bar Soaps' },
  { name: 'Menengai 1kg Carton',    retailPrice: 4200, wholesalePrice: 3990, category: 'Bar Soaps' },
  { name: 'Menengai 1kg 5pcs',      retailPrice: 1150, wholesalePrice: 1090, category: 'Bar Soaps' },
  { name: 'Big Boss 1kg',           retailPrice: 1650, wholesalePrice: 1560, category: 'Bar Soaps' },
  { name: 'Classic Bar 1kg',        retailPrice: 1650, wholesalePrice: 1560, category: 'Bar Soaps' },
  { name: 'Jamaa Cream 1kg',        retailPrice: 1900, wholesalePrice: 1800, category: 'Bar Soaps' },
  { name: 'Jamaa Cream 800g 12pcs', retailPrice: 1900, wholesalePrice: 1800, category: 'Bar Soaps' },
  { name: 'Ndume 1kg',              retailPrice: 1650, wholesalePrice: 1560, category: 'Bar Soaps' },
  { name: 'Meta 1kg',               retailPrice: 1680, wholesalePrice: 1596, category: 'Bar Soaps' },
  { name: 'Msafi Bar Soap 1kg',     retailPrice: 1650, wholesalePrice: 1560, category: 'Bar Soaps' },
  { name: 'Zenta Bar 1kg',          retailPrice: 1680, wholesalePrice: 1596, category: 'Bar Soaps' },
  { name: 'Zenta 800g',             retailPrice: 1680, wholesalePrice: 1596, category: 'Bar Soaps' },
  { name: 'Zenta 600g',             retailPrice: 1500, wholesalePrice: 1425, category: 'Bar Soaps' },
  { name: 'White Wash Carton',      retailPrice: 1600, wholesalePrice: 1400, category: 'Bar Soaps' },
  { name: 'Sunlight 50g Bar',       retailPrice: 970,  wholesalePrice: 920,  category: 'Bar Soaps' },
  { name: 'Sawa 125g',              retailPrice: 1800, wholesalePrice: 1710, category: 'Bar Soaps' },
  { name: 'Sawa 225g',              retailPrice: 1850, wholesalePrice: 1757, category: 'Bar Soaps' },
  { name: 'Geisha 200g 24pcs',      retailPrice: 2400, wholesalePrice: 2280, category: 'Bar Soaps' },
  { name: 'Geisha 90g 36pcs',       retailPrice: 1650, wholesalePrice: 1567, category: 'Bar Soaps' },
  { name: 'Dettol 60g 22pcs',       retailPrice: 3850, wholesalePrice: 3657, category: 'Bar Soaps' },
  { name: 'Dettol 90g Carton',      retailPrice: 8800, wholesalePrice: 8360, category: 'Bar Soaps' },
  { name: 'Detrex 80g',             retailPrice: 1900, wholesalePrice: 1805, category: 'Bar Soaps' },

  // ── POWDER SOAPS ──
  { name: 'Sunlight 30g Carton',   retailPrice: 1250, wholesalePrice: 1100, category: 'Powder Soaps' },
  { name: 'Sunlight 90g',          retailPrice: 1820, wholesalePrice: 1729, category: 'Powder Soaps' },
  { name: 'Sunlight 200g',         retailPrice: 2050, wholesalePrice: 1947, category: 'Powder Soaps' },
  { name: 'Sunlight 500g',         retailPrice: 4180, wholesalePrice: 3971, category: 'Powder Soaps' },
  { name: 'Sunlight 1kg',          retailPrice: 3800, wholesalePrice: 3610, category: 'Powder Soaps' },
  { name: 'Omo 20g Carton',        retailPrice: 1000, wholesalePrice: 950,  category: 'Powder Soaps' },
  { name: 'Omo 90g',               retailPrice: 1820, wholesalePrice: 1729, category: 'Powder Soaps' },
  { name: 'Omo 200g',              retailPrice: 3450, wholesalePrice: 3277, category: 'Powder Soaps' },
  { name: 'Omo 500g',              retailPrice: 4260, wholesalePrice: 4047, category: 'Powder Soaps' },
  { name: 'Ariel 20g Carton',      retailPrice: 1260, wholesalePrice: 1100, category: 'Powder Soaps' },
  { name: 'Ariel 45g',             retailPrice: 1230, wholesalePrice: 1168, category: 'Powder Soaps' },
  { name: 'Ariel 90g',             retailPrice: 1900, wholesalePrice: 1805, category: 'Powder Soaps' },
  { name: 'Ariel 200g',            retailPrice: 2750, wholesalePrice: 2612, category: 'Powder Soaps' },
  { name: 'Ariel 500g',            retailPrice: 4700, wholesalePrice: 4465, category: 'Powder Soaps' },
  { name: 'Ariel 1kg',             retailPrice: 4750, wholesalePrice: 4512, category: 'Powder Soaps' },
  { name: 'Msafi 500g Carton',     retailPrice: 1320, wholesalePrice: 1254, category: 'Powder Soaps' },
  { name: 'Msafi 1kg Carton',      retailPrice: 1320, wholesalePrice: 1254, category: 'Powder Soaps' },
  { name: 'Kleesoft 500g 20pcs',   retailPrice: 1600, wholesalePrice: 1520, category: 'Powder Soaps' },
  { name: 'Kleesoft 1kg 10pcs',    retailPrice: 1600, wholesalePrice: 1520, category: 'Powder Soaps' },
  { name: 'Doffi Purple 500g',     retailPrice: 1400, wholesalePrice: 1330, category: 'Powder Soaps' },
  { name: 'Doffi Yellow 500g',     retailPrice: 1400, wholesalePrice: 1330, category: 'Powder Soaps' },
  { name: 'Doffi Blue 500g',       retailPrice: 1400, wholesalePrice: 1330, category: 'Powder Soaps' },
  { name: 'Doffi Pink 500g',       retailPrice: 1400, wholesalePrice: 1330, category: 'Powder Soaps' },
  { name: 'Doffi 10kg',            retailPrice: 1180, wholesalePrice: 1121, category: 'Powder Soaps' },
  { name: 'Toss Sachets Carton',   retailPrice: 600,  wholesalePrice: 570,  category: 'Powder Soaps' },
  { name: 'Toss 500g',             retailPrice: 1970, wholesalePrice: 1871, category: 'Powder Soaps' },
  { name: 'Toss 200g',             retailPrice: 1680, wholesalePrice: 1596, category: 'Powder Soaps' },
  { name: 'Toss 1kg',              retailPrice: 1850, wholesalePrice: 1757, category: 'Powder Soaps' },
  { name: 'Toss 3.5kg',            retailPrice: 1070, wholesalePrice: 1016, category: 'Powder Soaps' },

  // ── DIAPERS ──
  { name: 'Maya Bale',                    retailPrice: 2650, wholesalePrice: 2517, category: 'Diapers' },
  { name: 'Maya Large',                   retailPrice: 480,  wholesalePrice: 456,  category: 'Diapers' },
  { name: 'Maya Medium',                  retailPrice: 480,  wholesalePrice: 456,  category: 'Diapers' },
  { name: 'Maya Small',                   retailPrice: 480,  wholesalePrice: 456,  category: 'Diapers' },
  { name: 'Pretty Baby Pampers Bale',     retailPrice: 2650, wholesalePrice: 2517, category: 'Diapers' },
  { name: 'Pretty Baby Large Outer',      retailPrice: 450,  wholesalePrice: 427,  category: 'Diapers' },
  { name: 'Pretty Baby Medium Outer',     retailPrice: 450,  wholesalePrice: 427,  category: 'Diapers' },
  { name: 'Pretty Baby Small Outer',      retailPrice: 450,  wholesalePrice: 427,  category: 'Diapers' },
  { name: 'Softcare HC XL',               retailPrice: 680,  wholesalePrice: 646,  category: 'Diapers' },
  { name: 'Softcare HC Large',            retailPrice: 680,  wholesalePrice: 646,  category: 'Diapers' },
  { name: 'Softcare HC Medium',           retailPrice: 680,  wholesalePrice: 646,  category: 'Diapers' },
  { name: 'Softcare HC Small',            retailPrice: 680,  wholesalePrice: 646,  category: 'Diapers' },
  { name: 'Softcare High Count Bale',     retailPrice: 3980, wholesalePrice: 3781, category: 'Diapers' },
  { name: 'Softcare Low Count Bale',      retailPrice: 1590, wholesalePrice: 1510, category: 'Diapers' },
  { name: 'Softcare LC Large',            retailPrice: 135,  wholesalePrice: 128,  category: 'Diapers' },
  { name: 'Softcare LC Medium',           retailPrice: 135,  wholesalePrice: 128,  category: 'Diapers' },
  { name: 'Softcare LC Small',            retailPrice: 135,  wholesalePrice: 128,  category: 'Diapers' },
  { name: 'Kisskids Sky Blue Bale',       retailPrice: 3200, wholesalePrice: 3040, category: 'Diapers' },
  { name: 'Kisskids Sky Blue Medium',     retailPrice: 570,  wholesalePrice: 541,  category: 'Diapers' },
  { name: 'Kisskids Sky Blue Large',      retailPrice: 570,  wholesalePrice: 541,  category: 'Diapers' },
  { name: 'Kisskids Sky Blue Small',      retailPrice: 570,  wholesalePrice: 541,  category: 'Diapers' },
  { name: 'Kisskids Dark Blue Bale',      retailPrice: 2750, wholesalePrice: 2612, category: 'Diapers' },
  { name: 'Kisskids Dark Blue Large',     retailPrice: 480,  wholesalePrice: 456,  category: 'Diapers' },
  { name: 'Kisskids Dark Blue Medium',    retailPrice: 480,  wholesalePrice: 456,  category: 'Diapers' },
  { name: 'Kisskids Dark Blue Small',     retailPrice: 480,  wholesalePrice: 456,  category: 'Diapers' },

  // ── SANITARY PADS ──
  { name: 'My Girl Carton',               retailPrice: 1550, wholesalePrice: 1472, category: 'Sanitary Pads' },
  { name: 'Sunny Girl Carton',            retailPrice: 2800, wholesalePrice: 2660, category: 'Sanitary Pads' },
  { name: 'Sunny Girl Dozen',             retailPrice: 700,  wholesalePrice: 665,  category: 'Sanitary Pads' },
  { name: 'Always Maxi Pink',             retailPrice: 1300, wholesalePrice: 1235, category: 'Sanitary Pads' },
  { name: 'Always Extra Long Blue',       retailPrice: 1800, wholesalePrice: 1710, category: 'Sanitary Pads' },
  { name: 'A+ Pad Carton',                retailPrice: 3950, wholesalePrice: 3752, category: 'Sanitary Pads' },
  { name: 'Softcare Pads Carton',         retailPrice: 1580, wholesalePrice: 1501, category: 'Sanitary Pads' },
  { name: 'Softcare Pad 6pcs',            retailPrice: 400,  wholesalePrice: 380,  category: 'Sanitary Pads' },
  { name: 'Softcare Pad 12pcs',           retailPrice: 800,  wholesalePrice: 760,  category: 'Sanitary Pads' },

  // ── WIPES ──
  { name: 'Softcare Baby Wipes',          retailPrice: 1600, wholesalePrice: 1520, category: 'Wipes' },
  { name: 'Softcare Wipes Outer',         retailPrice: 140,  wholesalePrice: 133,  category: 'Wipes' },
  { name: 'Bella Baby Wipes 12pcs',       retailPrice: 1350, wholesalePrice: 1282, category: 'Wipes' },
  { name: 'Aryuv Baby Wipes 12pcs',       retailPrice: 3650, wholesalePrice: 3467, category: 'Wipes' },

  // ── SNACKS & SWEETS ──
  { name: 'Big Daddy',                    retailPrice: 290,  wholesalePrice: 275,  category: 'Snacks & Sweets' },
  { name: 'Big Giant Assorted',           retailPrice: 290,  wholesalePrice: 275,  category: 'Snacks & Sweets' },
  { name: 'Big Giant Passion',            retailPrice: 290,  wholesalePrice: 275,  category: 'Snacks & Sweets' },
  { name: 'Big Giant Strawberry',         retailPrice: 290,  wholesalePrice: 275,  category: 'Snacks & Sweets' },
  { name: 'Big Giant Tongue Painter',     retailPrice: 290,  wholesalePrice: 275,  category: 'Snacks & Sweets' },
  { name: 'Ting Ting Assorted',           retailPrice: 210,  wholesalePrice: 199,  category: 'Snacks & Sweets' },
  { name: 'Ting Ting Cola',               retailPrice: 210,  wholesalePrice: 199,  category: 'Snacks & Sweets' },
  { name: 'Ting Ting Mango',              retailPrice: 210,  wholesalePrice: 199,  category: 'Snacks & Sweets' },
  { name: 'Juicy Fruit Small',            retailPrice: 400,  wholesalePrice: 380,  category: 'Snacks & Sweets' },
  { name: 'Juicy Fruit Big',              retailPrice: 600,  wholesalePrice: 570,  category: 'Snacks & Sweets' },
  { name: 'Fresh Peppermint',             retailPrice: 300,  wholesalePrice: 285,  category: 'Snacks & Sweets' },
  { name: 'Fresh Fruity',                 retailPrice: 300,  wholesalePrice: 285,  category: 'Snacks & Sweets' },
  { name: 'Fresh Menthol',                retailPrice: 300,  wholesalePrice: 285,  category: 'Snacks & Sweets' },
  { name: 'PK',                           retailPrice: 380,  wholesalePrice: 361,  category: 'Snacks & Sweets' },
  { name: 'Tajiri Pop',                   retailPrice: 200,  wholesalePrice: 190,  category: 'Snacks & Sweets' },
  { name: 'Ice Cool Mountain',            retailPrice: 190,  wholesalePrice: 180,  category: 'Snacks & Sweets' },
  { name: 'Kiboko Pop',                   retailPrice: 300,  wholesalePrice: 285,  category: 'Snacks & Sweets' },
  { name: 'Tamarindos Candy Balls',       retailPrice: 200,  wholesalePrice: 190,  category: 'Snacks & Sweets' },
  { name: 'Patco 500g',                   retailPrice: 150,  wholesalePrice: 142,  category: 'Snacks & Sweets' },
  { name: 'Patco 1kg',                    retailPrice: 330,  wholesalePrice: 313,  category: 'Snacks & Sweets' },
  { name: 'Cool Cow',                     retailPrice: 120,  wholesalePrice: 114,  category: 'Snacks & Sweets' },
  { name: 'Koo Drop',                     retailPrice: 150,  wholesalePrice: 142,  category: 'Snacks & Sweets' },
  { name: 'Tropical 500g',                retailPrice: 200,  wholesalePrice: 190,  category: 'Snacks & Sweets' },
  { name: 'Tropical 1kg',                 retailPrice: 400,  wholesalePrice: 380,  category: 'Snacks & Sweets' },
  { name: 'Tropical Lollipop 20pcs',      retailPrice: 170,  wholesalePrice: 161,  category: 'Snacks & Sweets' },
  { name: 'Big G Original',               retailPrice: 190,  wholesalePrice: 180,  category: 'Snacks & Sweets' },
  { name: 'Explode',                      retailPrice: 170,  wholesalePrice: 161,  category: 'Snacks & Sweets' },
  { name: 'Mabuyuz',                      retailPrice: 110,  wholesalePrice: 104,  category: 'Snacks & Sweets' },
  { name: 'Gomba',                        retailPrice: 150,  wholesalePrice: 142,  category: 'Snacks & Sweets' },
  { name: 'Gomba Carton',                 retailPrice: 2880, wholesalePrice: 2736, category: 'Snacks & Sweets' },
  { name: 'Nuvita Milky',                 retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Nuvita Lemon',                 retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Nuvita Crunchy Ginger',        retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Ginger Manji Biscuit',         retailPrice: 270,  wholesalePrice: 256,  category: 'Snacks & Sweets' },
  { name: 'Happy Happy Chocolate',        retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Happy Happy Strawberry',       retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Happy Happy Orange',           retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Happy Happy Mango',            retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Happy Happy Pineapple',        retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Happy Happy Vanilla',          retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Krackles Crisps 48pcs',        retailPrice: 2250, wholesalePrice: 2137, category: 'Snacks & Sweets' },
  { name: 'Ringos Barbeque',              retailPrice: 440,  wholesalePrice: 418,  category: 'Snacks & Sweets' },
  { name: 'Bitez',                        retailPrice: 440,  wholesalePrice: 418,  category: 'Snacks & Sweets' },
  { name: 'Princess',                     retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Yummy',                        retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Fun Time',                     retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Fun Toys',                     retailPrice: 260,  wholesalePrice: 247,  category: 'Snacks & Sweets' },
  { name: 'Glucose Excel 50g Carton',     retailPrice: 1400, wholesalePrice: 1330, category: 'Snacks & Sweets' },
  { name: 'Glucose Excel Sachets Outer',  retailPrice: 190,  wholesalePrice: 180,  category: 'Snacks & Sweets' },
  { name: 'Dairy Milk 80g 24pcs',         retailPrice: 5960, wholesalePrice: 5662, category: 'Snacks & Sweets' },
  { name: 'Dairy Milk Chocolate 35g',     retailPrice: 1350, wholesalePrice: 1282, category: 'Snacks & Sweets' },
  { name: 'Dairy Milk 9g',                retailPrice: 550,  wholesalePrice: 522,  category: 'Snacks & Sweets' },
  { name: 'Prince Chocolate 50g',         retailPrice: 350,  wholesalePrice: 332,  category: 'Snacks & Sweets' },
  { name: 'Oreo 26g',                     retailPrice: 550,  wholesalePrice: 522,  category: 'Snacks & Sweets' },
  { name: 'Oreo 52.5g',                   retailPrice: 750,  wholesalePrice: 712,  category: 'Snacks & Sweets' },

  // ── TOMATO SAUCE ──
  { name: 'Tomato Sauce 5ltrs 4pcs',      retailPrice: 1000, wholesalePrice: 950,  category: 'Tomato Sauce & Paste' },
  { name: 'Tomato Sauce 400ml 24pcs',     retailPrice: 1450, wholesalePrice: 1377, category: 'Tomato Sauce & Paste' },
  { name: 'Tomato Sauce 250ml 24pcs',     retailPrice: 1000, wholesalePrice: 950,  category: 'Tomato Sauce & Paste' },
  { name: 'Tomato Sauce Sachets 20ml 300pcs', retailPrice: 1000, wholesalePrice: 950, category: 'Tomato Sauce & Paste' },
  { name: 'Tamtam Paste 50g Outer',       retailPrice: 380,  wholesalePrice: 361,  category: 'Tomato Sauce & Paste' },
  { name: 'Tamtam Paste 50g Carton',      retailPrice: 1450, wholesalePrice: 1377, category: 'Tomato Sauce & Paste' },
  { name: 'Farajelo Paste 50g',           retailPrice: 1500, wholesalePrice: 1425, category: 'Tomato Sauce & Paste' },
  { name: 'Ken Tomato Paste 50g',         retailPrice: 1500, wholesalePrice: 1425, category: 'Tomato Sauce & Paste' },
  { name: 'Safi Tomato Paste 50g Carton', retailPrice: 1000, wholesalePrice: 950,  category: 'Tomato Sauce & Paste' },
  { name: 'Safi Tomato Paste Outer',      retailPrice: 270,  wholesalePrice: 256,  category: 'Tomato Sauce & Paste' },

  // ── CHILLI SAUCE ──
  { name: 'Nector Chilli Sauce 5ltrs 4pcs',   retailPrice: 1100, wholesalePrice: 1045, category: 'Chilli Sauce & Condiments' },
  { name: 'Nector Chilli Sauce 250ml 24pcs',  retailPrice: 1000, wholesalePrice: 950,  category: 'Chilli Sauce & Condiments' },
  { name: 'Executive Chilli Sauce 5ltr',      retailPrice: 1150, wholesalePrice: 1092, category: 'Chilli Sauce & Condiments' },
  { name: 'Executive Chilli Sauce 250ml',     retailPrice: 1050, wholesalePrice: 997,  category: 'Chilli Sauce & Condiments' },
  { name: 'Amigo Chilli Sauce 5ltrs',         retailPrice: 1000, wholesalePrice: 950,  category: 'Chilli Sauce & Condiments' },
  { name: 'Amigo Chilli Sauce 250ml',         retailPrice: 1000, wholesalePrice: 950,  category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Red Plum Jam 20g Sachet',    retailPrice: 1000, wholesalePrice: 950,  category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Red Jam 100g Dozen',         retailPrice: 550,  wholesalePrice: 522,  category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Red Plum Jam 450g',          retailPrice: 2200, wholesalePrice: 2090, category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Red Plum Jam 300g',          retailPrice: 1950, wholesalePrice: 1852, category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Red Jam 500g Dozen',         retailPrice: 2700, wholesalePrice: 2565, category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Red Jam 900g Dozen',         retailPrice: 3450, wholesalePrice: 3277, category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Hot & Sweet 720ml 12pcs',    retailPrice: 2000, wholesalePrice: 1900, category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Hot & Sweet 420ml 12pcs',    retailPrice: 2450, wholesalePrice: 2327, category: 'Chilli Sauce & Condiments' },
  { name: 'Zesta Hot & Sweet 250ml 24pcs',    retailPrice: 1800, wholesalePrice: 1710, category: 'Chilli Sauce & Condiments' },
  { name: 'Mayonnaise 946ml Carton',          retailPrice: 4250, wholesalePrice: 450,  category: 'Chilli Sauce & Condiments' },
  { name: 'Mayonnaise 473ml Carton',          retailPrice: 3000, wholesalePrice: 350,  category: 'Chilli Sauce & Condiments' },
  { name: 'Soy Sauce Dark 625ml Carton',      retailPrice: 2950, wholesalePrice: 2802, category: 'Chilli Sauce & Condiments' },
  { name: 'Soy Sauce Dark 150ml',             retailPrice: 2650, wholesalePrice: 175,  category: 'Chilli Sauce & Condiments' },
  { name: 'Soy Sauce Light 625ml',            retailPrice: 2550, wholesalePrice: 275,  category: 'Chilli Sauce & Condiments' },
  { name: 'Soy Sauce Light 150ml',            retailPrice: 2650, wholesalePrice: 155,  category: 'Chilli Sauce & Condiments' },

].map(p => ({
  description: `${p.name} - Quality product from Cerestrial Ventures`,
  countInStock: 100,
  brand: p.name.split(' ')[0],
  rating: 0,
  numReviews: 0,
  image: getImage(p.category),
  ...p,
  wholesalePrice: p.wholesalePrice ?? Math.round(p.retailPrice * 0.95),
}))

function getImage(category) {
  const images = {
    'Maize Flour':                'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
    'Cooking Fat':                'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    'Salad Oil':                  'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    'Pishori Rice':               'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Parboiled Rice':             'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Basmati Rice':               'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Biryani Rice':               'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Milk':                       'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    'Pastry & Food Products':     'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    'Coffee, Chocolate & Tea':    'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400',
    'Sugar':                      'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400',
    'Wheat Flour':                'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    'Salt':                       'https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?w=400',
    'Spreads':                    'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400',
    'Yeast':                      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    'Spices':                     'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400',
    'Bar Soaps':                  'https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=400',
    'Powder Soaps':               'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400',
    'Diapers':                    'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    'Sanitary Pads':              'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
    'Wipes':                      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    'Snacks & Sweets':            'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400',
    'Tomato Sauce & Paste':       'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400',
    'Chilli Sauce & Condiments':  'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400',
  }
  return images[category] || 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400'
}

mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/cerestrial')
  .then(async () => {
    console.log('✅ Connected to MongoDB')
    await Product.deleteMany({
      category: {
        $in: [
          'Maize Flour', 'Cooking Fat', 'Salad Oil',
          'Pishori Rice', 'Parboiled Rice', 'Basmati Rice', 'Biryani Rice',
          'Milk', 'Pastry & Food Products', 'Coffee, Chocolate & Tea',
          'Sugar', 'Wheat Flour',
          'Salt', 'Spreads', 'Yeast', 'Spices', 'Bar Soaps',
          'Powder Soaps', 'Diapers', 'Sanitary Pads', 'Wipes',
          'Snacks & Sweets', 'Tomato Sauce & Paste', 'Chilli Sauce & Condiments'
        ]
      }
    })
    console.log('🗑️ Cleared old products')
    await Product.insertMany(allProducts)
    console.log(`✅ Added ${allProducts.length} products successfully!`)
    mongoose.disconnect()
  })
  .catch(err => {
    console.error('❌ Error:', err.message)
    mongoose.disconnect()
  })