import mongoose from 'mongoose'
import dotenv from 'dotenv'
import Product from './models/Product.js'

dotenv.config()

const allProducts = [

  // ── MAIZE FLOUR ──
  { name: 'Riri Ugali 2kg',        retailPrice: 1950, category: 'Maize Flour' },
  { name: 'Riri Ugali 1kg',        retailPrice: 1980, category: 'Maize Flour' },
  { name: 'Leah Premium 2kg',      retailPrice: 2070, category: 'Maize Flour' },
  { name: 'Leah Premium 1kg',      retailPrice: 2090, category: 'Maize Flour' },
  { name: 'Nice Premium 2kg',      retailPrice: 2280, category: 'Maize Flour' },
  { name: 'Nice Premium 1kg',      retailPrice: 2300, category: 'Maize Flour' },
  { name: 'Raha Premium 2kg',      retailPrice: 2280, category: 'Maize Flour' },
  { name: 'Raha Premium 1kg',      retailPrice: 2300, category: 'Maize Flour' },
  { name: 'Spenza 2kg',            retailPrice: 2150, category: 'Maize Flour' },
  { name: 'Spenza 1kg',            retailPrice: 2180, category: 'Maize Flour' },
  { name: 'Soko Ugali 2kg',        retailPrice: 1900, category: 'Maize Flour' },
  { name: 'Soko Ugali 1kg',        retailPrice: 1920, category: 'Maize Flour' },
  { name: '210 Ugali 2kg',         retailPrice: 1880, category: 'Maize Flour' },
  { name: '210 Ugali 1kg',         retailPrice: 1900, category: 'Maize Flour' },
  { name: 'Pembe Ugali 2kg',       retailPrice: 1900, category: 'Maize Flour' },
  { name: 'Pembe Ugali 1kg',       retailPrice: 1920, category: 'Maize Flour' },
  { name: 'Diamond Ugali 2kg',     retailPrice: 1600, category: 'Maize Flour' },
  { name: 'Diamond Ugali 1kg',     retailPrice: 1630, category: 'Maize Flour' },
  { name: 'Jasiri Ugali 2kg',      retailPrice: 1630, category: 'Maize Flour' },
  { name: 'Jasiri Ugali 1kg',      retailPrice: 1650, category: 'Maize Flour' },
  { name: 'Rania Ugali 2kg',       retailPrice: 1600, category: 'Maize Flour' },
  { name: 'Rania Ugali 1kg',       retailPrice: 1630, category: 'Maize Flour' },
  { name: 'Dhahabu Ugali 2kg',     retailPrice: 1570, category: 'Maize Flour' },
  { name: 'Dhahabu Ugali 1kg',     retailPrice: 1600, category: 'Maize Flour' },
  { name: 'Miale Ugali 2kg',       retailPrice: 1570, category: 'Maize Flour' },
  { name: 'Miale Ugali 1kg',       retailPrice: 1600, category: 'Maize Flour' },

  // ── COOKING FAT ──
  { name: 'Samli 10kg',            retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Pika 10kg',             retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Seagull 10kg',          retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Sunshine 10kg',         retailPrice: 2550, category: 'Cooking Fat' },
  { name: 'Zulfa 10kg',            retailPrice: 2550, category: 'Cooking Fat' },

  // ── SALAD OIL ──
  { name: 'Rina Salad Oil 5ltrs 4pcs',     retailPrice: 5450, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 3ltrs 6pcs',     retailPrice: 4720, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 2ltrs 8pcs',     retailPrice: 4250, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 1ltr 12pcs',     retailPrice: 3390, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 500ml 12pcs',    retailPrice: 1750, category: 'Salad Oil' },
  { name: 'Rina Salad Oil 250ml 24pcs',    retailPrice: 1900, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 1ltr',         retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 2ltrs',        retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 3ltrs',        retailPrice: 4650, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 5ltrs',        retailPrice: 5150, category: 'Salad Oil' },
  { name: 'Halisi Salad Oil 20ltrs',       retailPrice: 5050, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 1ltr',           retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 2ltrs',          retailPrice: 3300, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 3ltrs',          retailPrice: 4650, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 5ltrs',          retailPrice: 5150, category: 'Salad Oil' },
  { name: 'Somo Salad Oil 20ltrs',         retailPrice: 5050, category: 'Salad Oil' },
  { name: 'Fresh Fri 250ml 24pcs',         retailPrice: 2350, category: 'Salad Oil' },
  { name: 'Fresh Fri 500ml 12pcs',         retailPrice: 2150, category: 'Salad Oil' },
  { name: 'Fresh Fri 1ltr 12pcs',          retailPrice: 3700, category: 'Salad Oil' },
  { name: 'Fresh Fri 2ltrs 6pcs',          retailPrice: 3750, category: 'Salad Oil' },
  { name: 'Fresh Fri 3ltrs 6pcs',          retailPrice: 5200, category: 'Salad Oil' },
  { name: 'Fresh Fri 5ltrs 4pcs',          retailPrice: 5550, category: 'Salad Oil' },
  { name: 'Fresh Fri 5ltrs 1pc',           retailPrice: 1370, category: 'Salad Oil' },
  { name: 'Popco Salad Oil 5ltrs',         retailPrice: 1300, category: 'Salad Oil' },
  { name: 'Golden Drop 20ltrs',            retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Pura 20ltrs',                   retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Postman 20ltrs',                retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Postman 10ltrs',                retailPrice: 2600, category: 'Salad Oil' },
  { name: 'Pika Salad Oil 20ltrs',         retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Salit 20ltrs',                  retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Nyota 20ltrs',                  retailPrice: 5080, category: 'Salad Oil' },
  { name: 'Nyota 10ltrs',                  retailPrice: 2600, category: 'Salad Oil' },
  { name: 'Karaih 20ltrs',                 retailPrice: 5050, category: 'Salad Oil' },
  { name: 'Karaih 10ltrs',                 retailPrice: 2600, category: 'Salad Oil' },

  // ── PISHORI RICE ──
  { name: 'Mwea Pure Pishori Rice 25kg',   retailPrice: 3800, category: 'Pishori Rice' },

  // ── PARBOILED RICE ──
  { name: 'Rischi Parboiled 25kg',         retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Raha Parboiled 25kg',           retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Volga Parboiled 25kg',          retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'King Africa Parboiled 25kg',    retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Maarufu Parboiled 25kg',        retailPrice: 2850, category: 'Parboiled Rice' },
  { name: 'Najah PK386 25kg',              retailPrice: 4200, category: 'Parboiled Rice' },
  { name: 'King Africa PK386 25kg',        retailPrice: 3450, category: 'Parboiled Rice' },
  { name: 'Alrazq 25kg',                   retailPrice: 3650, category: 'Parboiled Rice' },
  { name: 'Mzuri PK386 25kg',              retailPrice: 3600, category: 'Parboiled Rice' },
  { name: 'Zahra 25kg',                    retailPrice: 3900, category: 'Parboiled Rice' },
  { name: 'Shabeel 25kg',                  retailPrice: 4200, category: 'Parboiled Rice' },
  { name: 'Karama 25kg',                   retailPrice: 4300, category: 'Parboiled Rice' },
  { name: 'Hamza Parboiled 25kg',          retailPrice: 4350, category: 'Parboiled Rice' },
  { name: 'ANFAC Long Grain 25kg',         retailPrice: 5700, category: 'Parboiled Rice' },
  { name: 'Mahamood 1121 25kg',            retailPrice: 6000, category: 'Parboiled Rice' },

  // ── BASMATI RICE ──
  { name: 'Joli Marhaba Basmati 25kg',     retailPrice: 3250, category: 'Basmati Rice' },
  { name: 'Azmat Basmati 25kg',            retailPrice: 3250, category: 'Basmati Rice' },
  { name: 'Fzami Poa 25kg',               retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Fzami Karibu 25kg',             retailPrice: 3400, category: 'Basmati Rice' },
  { name: 'Kangore Gold Basmati 25kg',     retailPrice: 3350, category: 'Basmati Rice' },
  { name: 'Sanaa Brown 25kg',              retailPrice: 3450, category: 'Basmati Rice' },
  { name: 'Amne Basmati 25kg',             retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Indus Basmati 25kg',            retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Hanaan Basmati 25kg',           retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Hani Basmati 25kg',             retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Siham Basmati 25kg',            retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Yabal Brown 25kg',              retailPrice: 3800, category: 'Basmati Rice' },
  { name: 'Baraf Brown 25kg',              retailPrice: 3800, category: 'Basmati Rice' },
  { name: 'Halwo Brown 25kg',              retailPrice: 3800, category: 'Basmati Rice' },
  { name: 'Safi Special Sindano 25kg',     retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Mankera Special Sindano 25kg',  retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Indus PK386 25kg',              retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Star Africa PK386 25kg',        retailPrice: 3450, category: 'Basmati Rice' },
  { name: 'Indus 555 25kg',               retailPrice: 3500, category: 'Basmati Rice' },
  { name: 'Mahia White 25kg',              retailPrice: 3550, category: 'Basmati Rice' },
  { name: 'Capital White 25kg',            retailPrice: 3650, category: 'Basmati Rice' },
  { name: 'Jawil Gold 25kg',               retailPrice: 3650, category: 'Basmati Rice' },
  { name: 'Fzami Sindano Safi 25kg',       retailPrice: 3200, category: 'Basmati Rice' },
  { name: 'Fzami Sindano Bora 25kg',       retailPrice: 3300, category: 'Basmati Rice' },
  { name: 'Anab PK386 25kg',               retailPrice: 3650, category: 'Basmati Rice' },
  { name: 'Hanan PK386 25kg',              retailPrice: 3650, category: 'Basmati Rice' },

  // ── BIRYANI RICE ──
  { name: 'Manaan Biryani 25kg',           retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Maarufu Biryani 25kg',          retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Kuku Biryani 25kg',             retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Dream Africa Biryani 25kg',     retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Indian Biryani 25kg',           retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Indus Biryani Gold 25kg',       retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Raha Biryani 25kg',             retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Sakshi Biryani 25kg',           retailPrice: 2500, category: 'Biryani Rice' },
  { name: 'Rischi Biryani 25kg',           retailPrice: 2550, category: 'Biryani Rice' },
  { name: 'Fineese Biryani 25kg',          retailPrice: 2580, category: 'Biryani Rice' },

  // ── MILK ──
  { name: 'Mt Kenya Milk 500ml 18pcs',     retailPrice: 930,  category: 'Milk' },
  { name: 'Mt Kenya Milk 200ml 21pcs',     retailPrice: 520,  category: 'Milk' },
  { name: 'Daima Milk 500ml 18pcs',        retailPrice: 920,  category: 'Milk' },
  { name: 'Brookside Milk 500ml 12pcs',    retailPrice: 750,  category: 'Milk' },
  { name: 'Brookside Milk 200ml 21pcs',    retailPrice: 650,  category: 'Milk' },
  { name: 'Lato Milk 18pcs',               retailPrice: 950,  category: 'Milk' },

  // ── PASTRY & FOOD PRODUCTS ──
  { name: 'Indomie Supermi',               retailPrice: 650,  category: 'Pastry & Food Products' },
  { name: 'Indomie Chicken',               retailPrice: 750,  category: 'Pastry & Food Products' },
  { name: 'Indomie Beef',                  retailPrice: 750,  category: 'Pastry & Food Products' },
  { name: 'Nala Noodles',                  retailPrice: 700,  category: 'Pastry & Food Products' },
  { name: 'Rosa Spaghetti 500g',           retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Nureen Spaghetti 500g',         retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Indus Spaghetti 500g',          retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Siens Spaghetti 500g',          retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Arta Spaghetti',                retailPrice: 2250, category: 'Pastry & Food Products' },
  { name: 'Salsa Spaghetti 500g',          retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Sara Spaghetti 500g',           retailPrice: 1350, category: 'Pastry & Food Products' },
  { name: 'Tak Spaghetti 500g',            retailPrice: 2350, category: 'Pastry & Food Products' },
  { name: 'Tak Macaroni 500g',             retailPrice: 2350, category: 'Pastry & Food Products' },
  { name: 'Hilwa 500g x12',                retailPrice: 800,  category: 'Pastry & Food Products' },
  { name: 'Cerelac 25g x12',               retailPrice: 500,  category: 'Pastry & Food Products' },
  { name: 'Cerelac 50g x12',               retailPrice: 800,  category: 'Pastry & Food Products' },
  { name: 'Cerelac 400g 1pc',              retailPrice: 850,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 37g 2dzn',             retailPrice: 620,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 74g',                  retailPrice: 1160, category: 'Pastry & Food Products' },
  { name: 'Weetabix 112g',                 retailPrice: 2100, category: 'Pastry & Food Products' },
  { name: 'Weetabix 210g Carton',          retailPrice: 8550, category: 'Pastry & Food Products' },
  { name: 'Weetabix 210g Dozen',           retailPrice: 250,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 425g Carton',          retailPrice: 8200, category: 'Pastry & Food Products' },
  { name: 'Weetabix 425g Dozen',           retailPrice: 460,  category: 'Pastry & Food Products' },
  { name: 'Weetabix 850g Carton',          retailPrice: 7300, category: 'Pastry & Food Products' },
  { name: 'Weetabix 850g Dozen',           retailPrice: 700,  category: 'Pastry & Food Products' },
  { name: 'Weetos 420g x8 Carton',         retailPrice: 4350, category: 'Pastry & Food Products' },
  { name: 'Weetos 420g Piece',             retailPrice: 600,  category: 'Pastry & Food Products' },
  { name: 'Salama Oats 1kg x9 Carton',     retailPrice: 2500, category: 'Pastry & Food Products' },
  { name: 'Salama Oats 1kg Piece',         retailPrice: 350,  category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 35g Carton', retailPrice: 1450, category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 35g Piece',  retailPrice: 250,  category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 70g Carton', retailPrice: 1750, category: 'Pastry & Food Products' },
  { name: 'Sossi Chicken/Beef 70g Piece',  retailPrice: 460,  category: 'Pastry & Food Products' },

  // ── COFFEE, CHOCOLATE & TEA ──
  { name: 'Cocoa Drinking 20g Dozen',          retailPrice: 650,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 90g Dozen',                   retailPrice: 3270, category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 200g Carton',                 retailPrice: 5850, category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 200g Dozen',                  retailPrice: 530,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 320g Carton',                 retailPrice: 11100,category: 'Coffee, Chocolate & Tea' },
  { name: 'Cocoa 320g Dozen',                  retailPrice: 1000, category: 'Coffee, Chocolate & Tea' },
  { name: 'Maccoffee Dozen',                   retailPrice: 95,   category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe Dozen',                     retailPrice: 110,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe Outer',                     retailPrice: 750,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 3 in 1 Outer',              retailPrice: 400,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 50g Dozen',                 retailPrice: 3270, category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 100g',                      retailPrice: 4900, category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 100g Piece',                retailPrice: 430,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 200g Carton',               retailPrice: 8500, category: 'Coffee, Chocolate & Tea' },
  { name: 'Nescafe 200g Piece',                retailPrice: 730,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 10g Outer',          retailPrice: 850,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 10g Piece',          retailPrice: 180,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 20g Outer',          retailPrice: 1065, category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Chocolate 20g Piece',          retailPrice: 300,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 160g Dozen',             retailPrice: 2500, category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 160g Piece',             retailPrice: 400,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 320g Dozen',             retailPrice: 7100, category: 'Coffee, Chocolate & Tea' },
  { name: 'Raha Cocoa 320g Piece',             retailPrice: 630,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 125g Dozen',     retailPrice: 2250, category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 125g Piece',     retailPrice: 230,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 225g Dozen',     retailPrice: 3700, category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 225g Piece',     retailPrice: 330,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 450g Dozen',     retailPrice: 6920, category: 'Coffee, Chocolate & Tea' },
  { name: 'Drinking Chocolate 450g Piece',     retailPrice: 650,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Milo 20g Dozen',                    retailPrice: 230,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Kahawa No.1 2 Dozen',               retailPrice: 260,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 1.6g 25pcs',                retailPrice: 300,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 1.6g 100pcs',               retailPrice: 950,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 50g',                       retailPrice: 370,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 100g',                      retailPrice: 670,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Dormans 200g',                      retailPrice: 1230, category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 15g',                       retailPrice: 150,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 50g',                       retailPrice: 200,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 100g',                      retailPrice: 480,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 250g 6pcs',                 retailPrice: 720,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Maramba 500g 6pcs',                 retailPrice: 1140, category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 250g',                       retailPrice: 500,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 100g',                       retailPrice: 450,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 50g x10',                    retailPrice: 230,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Ketepa 15g x50',                    retailPrice: 350,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 15g',                      retailPrice: 150,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 25g',                      retailPrice: 150,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 50g',                      retailPrice: 230,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 100g',                     retailPrice: 450,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 250g Piece',               retailPrice: 130,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Eden Tea 500g Piece',               retailPrice: 200,  category: 'Coffee, Chocolate & Tea' },
  { name: "Melvin's 15g",                      retailPrice: 180,  category: 'Coffee, Chocolate & Tea' },
  { name: "Melvin's 50g",                      retailPrice: 650,  category: 'Coffee, Chocolate & Tea' },
  { name: "Melvin's 100g",                     retailPrice: 650,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Kericho Tea Bags 50s',              retailPrice: 200,  category: 'Coffee, Chocolate & Tea' },
  { name: 'Kericho Tea Bags Envelope 100s',    retailPrice: 300,  category: 'Coffee, Chocolate & Tea' },

  // ── SUGAR ──
  { name: 'Sugar 50kg',                    retailPrice: 6800, category: 'Sugar' },
  { name: 'Sugar 25kg',                    retailPrice: 3450, category: 'Sugar' },
  { name: 'Kabras Sugar 1kg',              retailPrice: 3250, category: 'Sugar' },
  { name: 'Kabras Sugar 2kg',              retailPrice: 3250, category: 'Sugar' },
  { name: 'Sare Packed Sugar 1kg',         retailPrice: 3350, category: 'Sugar' },
  { name: 'Mara Sugar 1kg',                retailPrice: 3350, category: 'Sugar' },

  // ── WHEAT FLOUR ──
  { name: 'Raha Premium Ngano 2kg',        retailPrice: 1960, category: 'Wheat Flour' },
  { name: 'Riri Ngano 2kg',                retailPrice: 1870, category: 'Wheat Flour' },
  { name: 'Supreme Ngano 2kg',             retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Lotus Ngano 2kg',               retailPrice: 1930, category: 'Wheat Flour' },
  { name: 'Swan Wheat 2kg',                retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Umoja Ngano 2kg',               retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Umoja Ngano 1kg',               retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Exe Mandazi 2kg',               retailPrice: 2150, category: 'Wheat Flour' },
  { name: 'Self Raising Flour 2kg',        retailPrice: 2250, category: 'Wheat Flour' },
  { name: 'Ajab Ngano 2kg',                retailPrice: 2000, category: 'Wheat Flour' },
  { name: 'Ajab Ngano 1kg',                retailPrice: 2020, category: 'Wheat Flour' },
  { name: 'Ajab Ngano 500g',               retailPrice: 1050, category: 'Wheat Flour' },
  { name: 'Ndovu All Purpose 2kg',         retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Ndovu All Purpose 1kg',         retailPrice: 1920, category: 'Wheat Flour' },
  { name: '210 Ngano 2kg',                 retailPrice: 1900, category: 'Wheat Flour' },
  { name: '210 Ngano 1kg',                 retailPrice: 1920, category: 'Wheat Flour' },
  { name: 'Hodi Ngano 2kg',                retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Hodi Ngano 1kg',                retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Kifaru Ngano 2kg',              retailPrice: 1900, category: 'Wheat Flour' },
  { name: 'Kifaru Ngano 1kg',              retailPrice: 1920, category: 'Wheat Flour' },
  { name: 'Pembe Ngano 2kg',               retailPrice: 1880, category: 'Wheat Flour' },
  { name: 'Pembe Ngano 1kg',               retailPrice: 1910, category: 'Wheat Flour' },
  { name: 'Pembe Atta Mark 2kg',           retailPrice: 1970, category: 'Wheat Flour' },
  { name: 'Soko Ngano 2kg',                retailPrice: 1900, category: 'Wheat Flour' },

].map(p => ({
  ...p,
  wholesalePrice: Math.round(p.retailPrice * 0.95),
  description: `${p.name} - Quality product from Cerestrial Ventures`,
  countInStock: 100,
  brand: p.name.split(' ')[0],
  rating: 0,
  numReviews: 0,
  image: getImage(p.category),
}))

function getImage(category) {
  const images = {
    'Maize Flour':              'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
    'Cooking Fat':              'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    'Salad Oil':                'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    'Pishori Rice':             'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Parboiled Rice':           'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Basmati Rice':             'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Biryani Rice':             'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    'Milk':                     'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    'Pastry & Food Products':   'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    'Coffee, Chocolate & Tea':  'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400',
    'Sugar':                    'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400',
    'Wheat Flour':              'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
  }
  return images[category] || 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400'
}

mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/cerestrial')
  .then(async () => {
    console.log('✅ Connected to MongoDB')
    await Product.deleteMany({
      category: {
        $in: [
          'Maize Flour', 'Cooking Fat', 'Salad Oil',
          'Pishori Rice', 'Parboiled Rice', 'Basmati Rice', 'Biryani Rice',
          'Milk', 'Pastry & Food Products', 'Coffee, Chocolate & Tea',
          'Sugar', 'Wheat Flour'
        ]
      }
    })
    console.log('🗑️ Cleared old products')
    await Product.insertMany(allProducts)
    console.log(`✅ Added ${allProducts.length} products successfully!`)
    mongoose.disconnect()
  })
  .catch(err => {
    console.error('❌ Error:', err.message)
    mongoose.disconnect()
  })